version: "3.9"

services:
  lotsearch:
    build: .
    env_file:
      - .env
    environment:
      LOG_DIR: /app/logs
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
